pipeline {
    agent {
        kubernetes {
            label "sbgr2"
            defaultContainer "jnlp"
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: gradle
    image: gradle:latest
    command:
    - cat
    tty: true
"""
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        durabilityHint('PERFORMANCE_OPTIMIZED')
    }
    stages {
        stage("Prepare Build Environment") {
            steps {
                container("gradle") {
                    echo "${previewEnvHostname}"
                    echo "${emailRecipient}"
                    sh """
                        gradle --version
                    """
                }
            }
        }
    }
}
