
pipeline {
    agent {
        kubernetes {
            label "sbgr2"
            defaultContainer "jnlp"
            yamlFile "containers.yml"
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        durabilityHint('PERFORMANCE_OPTIMIZED')
    }
    stages {
        stage("Prepare Build Environment") {
            steps {
                container("gradle") {
                    echo "${previewEnvHostname}"
                    echo "${emailRecipient}"
                    sh """
                        gradle --version
                    """
                }
            }
        }
    }
}
