def gradle_pod_template = libraryResource 'pod-templates/gradle-template.yaml'

pipeline {
    agent {
        kubernetes {
            label "ghdp2"
            defaultContainer "jnlp"
            yaml gradle_pod_template
    }
  stages {
    stage('Build') {
      steps {
        sh """
          ./gradlew clean build
        """
      }
    }
  }
}
