pipeline {
    agent any
    stages {
        stage('Build') {
          steps {
            echo "${previewEnvHostname}"
            echo "${emailRecipient}"
            sh "./mvn clean install"
          }
        }
    }
}