pipeline {
    agent { label 'cloudbees-core' }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    echo "${previewEnvHostname}"
                    echo "${emailRecipient}"
                    sh "./mvn clean install"
                }
            }
        }
    }
}