pipeline {
    agent any
    options {
        durabilityHint("PERFORMANCE_OPTIMIZED")
        timeout(time: 3, unit: "DAYS")
        disableConcurrentBuilds()
        skipDefaultCheckout true
    }
    stages {
        stage("Checkout") {
          steps {
            checkout([$class: "GitSCM", 
              branches: [[name: "**"]], 
              doGenerateSubmoduleConfigurations: false, 
              extensions: [], 
              submoduleCfg: [], 
              userRemoteConfigs: [[credentialsId: "${gitCredentials}", url: "${repoUrl}"]]]
            )
          }
        }
        stage("Confirm Deploy") {
          agent none
          options {
            timeout(time: 12, unit: "HOURS") {
          }
          steps {
            input(message: "Approve Deploy?", ok: "Yes")
          }
        }
        stage("Deploy") {
          steps {
            echo "do the deploy"
          }
        }
    }
}
