pipeline {
    agent any
    options {
        durabilityHint "PERFORMANCE_OPTIMIZED"
    }
    stages {
        stage('Build') {
          steps {
            echo "${previewEnvHostname}"
            echo "${emailRecipient}"
          }
        }
    }
}
